### ISSUE TITLE
What version of pytorch did you use?

### ISSUE THREAD

**Issue by moFang222** [moskomule/ewc.pytorch#5]
Hi,moskomule! Great work!
I want to know what version of pytorch did you use? Because I can't reproduce your results. I am wondering if the problem appeared on the version of pytorch.

**Comment by moskomule** [comment]
Hi, I don't remember. But the last commit was 2 years ago, so it should be very old one...

**Comment by moFang222** [comment]
@moskomule Ok,thanks!
